### ISSUE TITLE
"System" CPU usage dropped from 40% to 5% with latest driver

### ISSUE THREAD

**Issue by epezent** [quanser/hil_sdk_win64#1]
Thought I would drop some feedback, since it was encouraged in the README. 

I have been running HIL 3.8.2414, and was seeing approximately 40% CPU usage from the "System" process in Task Manager. I noticed it only occurred while sampling my Q8-USB, which was unusual as this hasn't been an issue in the past. I found this repository, and upgraded to the latest driver (3.8.2866). Astoundingly, the CPU usage of "System" dropped to around 4-5% and the controller my Q8-USB was driving became significantly smoother in operation:

![image](https://user-images.githubusercontent.com/29577475/77241989-d7b74e80-6bc7-11ea-92a6-c2ab17dc9580.png)

My Windows 10 version:

Version 1803 Build 17134.1365

This is similar to a previous issue I was in email correspondence with you about several months ago. The conclusion that I came to was that it was related to a recent Windows 10 update which, at the time, was wrecking havoc for several USB devices. 

At any rate, this driver seems to resolve the issue. Thanks! Hope to see more releases here in the future.

**Comment by hlacheray** [comment]
Yes, I do remember our discussion of about 5 months ago. Thank you very much for the follow up and sharing the good news with us. We always truly appreciate user feedback. As you've noticed, we did do some important fixes around that time and in this release of our Windows HIL SDK. No worries, future updates will also be available here :)
