### ISSUE TITLE
C++ Classes for Q8-USB, QPID, and Q2-USB

### ISSUE THREAD

**Issue by epezent** [quanser/hil_sdk_win64#2]
Our [research lab](https://github.com/mahilab) makes significant use of Quanser products, as we have around a dozen Q8-USBs driving experimental hardware at the moment. As great as the MATLAB/Simulink interfaces are for these devices, we have, for the past few years, been using the lower level HIL SDK C functions instead because our projects are becoming more complex and demanding.

I wanted to share some work we've done in creating a library of C++ classes for various DAQs, including the Quanser Q8-USB, QPID, and Q2-USB. The main repository is located in [mahi-daq](https://github.com/mahilab/mahi-daq). The classes wrap much of the HIL SDK into easy to use object-oriented interfaces. Here's a tour de force of what the library offers:

### Opening and Configuration
```cpp
// open Q8-USB
Q8Usb q8;
// create DAQ specific options
QuanserOptions opts;
opts.encX_filter[0] = QuanserOptions::EncoderFilter::Filtered;
opts.encX_velocity[0] = 0.1;
opts.aoX_params[0].ch_mode = QuanserOptions::AoMode::CurrentMode1;
opts.aoX_params[0].ch_kff = 0;
opts.aoX_params[0].ch_a0 = 2;
opts.aoX_params[0].ch_a1 = 20;
opts.aoX_params[0].ch_a2 = 0;
opts.aoX_params[0].ch_b0 = -1;
opts.aoX_params[0].ch_b1 = 0;
opts.aoX_params[0].ch_post = 1000;
// set options
q8.set_options(opts);
```

### Synchronized Reads/Writes
```cpp
// synchronized reads
q8.read_all();
bool di0 = q8.DI[0];
double ai5 = q8.AI[5];
int enc3 = q8.encoder[3];
double vel2 = q8.velocity[2];
// synchronized writes
q8.DO[7] = true;
q8.AO[2] = 1.23;
q8.write_all();
```
### Per Module Reads/Writes
```cpp
q8.AI.read();
q8.AO[0] = q8.AI[7];
q8.AO.write();
```
### Per Channel Reads/Writes
```cpp
q8.DI.read(1);
q8.DO.write(1,q8.DI[1]);
```
### Set Enable/Disable/Expire Values
```cpp
q8.DO.enable_values[0] = true;
q8.AO.enable_values[0] = 3.14;
q8.AO.disable_values[0] = 0;
q8.AO.expire_values.write(0,0);
...
q8.enable(); // AO0 will go to 3.14 V, DO0 will go to 5 V
...
q8.disabe(); // AO0 will go to 0 V, DO0 will go to 0 V (default)
```

### Watchdog Support
```cpp
q8.watchdog.set_timeout(10_ms);
q8.watchdog.start();
while (true) {
    ...
    q8.watchdog.kick();
}
q8.watchdog.stop();
```

### Automatic Handling of Shared Pins
```cpp
q8.PWM.set_channels({0,1,2,3}); // converts DO 0:3 to PWM outputs
q8.PWM.frequencies.write(0, 20000);
q8.PWM.write(0, 0.75);
```
### Lightweight Handles for Individual Channels
```cpp
DOHandle h_do0(q8.DO, 0);
AOHandle h_ao0(q8.AO, 0);
EncoderHandle h_enc0(q8.encoder, 0);
// I/O through handles
h_do0.write_level(TTL_LOW);
h_ao0.write_volts(0);
h_enc0.write_mode(QuadMode::X4);
h_enc0.set_units(360.0 / 1024);
h_enc0.zero();
// pass handles to other classes
MyRobot rob(h_do0, h_ao0, h_enc0);
```

### Precision Timing Utilities
```cpp
Q8Usb q8;
Timer timer(1000_Hz);
Time t = Time::Zero;
while (t < 60_s) {
    q8.read_all();
    my_controller_update(t, q8.AO[0],q8.AI[0],q8.encoder[0]);
    q8.write_all();
    t = timer.wait();
}
```

The library is very easy to get started with and has reasonably well documented headers. Build instructions using CMake can be found on the repository's [README](https://github.com/mahilab/mahi-daq) page, and several examples are available [here](https://github.com/mahilab/mahi-daq/tree/master/examples). 

We hope that Quanser users and developers find this library useful, and we encourage contributions and feedback!

Evan Pezent (epezent@rice.edu)

**Comment by hlacheray** [comment]
Thank you Evan for sharing this very nice project extending the functionality of our HIL C API. 

Interestingly enough, support for the NI myRIO is also part of this release of our HIL SDK, as it has been added to QUARC (our real-time control software for MATLAB/Simulink) since version 2018. As QUARC uses the HIL SDK directly, most data acquisition cards listed in the hyperlink below are also supported by our Windows HIL SDK:  
[https://docs.quanser.com/quarc/documentation/quarc_supported_data_acquisition_cards.html](https://docs.quanser.com/quarc/documentation/quarc_supported_data_acquisition_cards.html)
You will notice a number of other cards, also from National Instruments and Sensoray, that may be also useful to you and your research group.
