### ISSUE TITLE
Matlab usage

### ISSUE THREAD

**Issue by ahmtkeles27** [quanser/hil_sdk_win64#3]
When trying to call the matlab functions after installation on windows, I get Invalid MEX-file mexfilename: The specified module could not be found error, what dependencies are there for me to use this on windows 10? Is the QUARC software requiered?

**Comment by hlacheray** [comment]
Thank you for reaching out. We actually found a missing dependency in this installer. We are also working on a new release that will be posted here next week. Would this timeline work on your end?

**Comment by ahmtkeles27** [comment]
Thank you very much, its more than perfect for me
